name: "Synapse Login"

description: "Log into Synapse"

inputs:
  username:
    description: "Synapse username"
    required: true

  apikey:
    description: "Synapse apikey"
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        printf "%s\n" \
          "[authentication]" \
          'username="${{ secrets.SYNAPSE_USERNAME }}"' \
          'apikey="${{ secrets.SYNAPSE_API_KEY }}"' | tee -a ~/.synapseConfig >/dev/null